# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8
    
development:
  <<: *default
  database: smud_development

test:
  <<: *default
  database: smud_test

production:
  <<: *default
  database: smud_production
  username:
  password:

